(() => {
  'use strict';

  const STEPS_PER_BEAT = 4, BEATS_PER_BAR = 4, STEPS_PER_BAR = 16, BARS_PER_PHRASE = 4, STEPS_PER_PHRASE = 64;
  const SECTIONS = Object.freeze({ CALM:'CALM', GROOVE:'GROOVE', BUILD:'BUILD', DROP:'DROP', RELEASE:'RELEASE' });
  const THEMES = Object.freeze({
    'NEON HORIZON': { bpm:112, root:45, scale:[0,2,3,7,9], lead:'sawtooth', bass:'square', cutoff:4200, mood:'synthwave', progressions:[[[0,3,7],[8,12,15],[3,7,10],[10,14,17]],[[0,3,7],[5,8,12],[8,12,15],[7,11,14]]] },
    'ORBITAL STATIC': { bpm:120, root:38, scale:[0,2,5,7,9], lead:'triangle', bass:'sawtooth', cutoff:5100, mood:'space pulse', progressions:[[[0,5,9],[2,7,12],[5,9,14],[0,7,12]],[[0,5,9],[7,12,16],[2,7,11],[5,9,14]]] },
    'MIDNIGHT CITY': { bpm:126, root:41, scale:[0,3,5,7,10], lead:'square', bass:'sawtooth', cutoff:3300, mood:'dark club', progressions:[[[0,3,7],[8,12,15],[3,7,10],[10,14,17]],[[0,3,7],[5,8,12],[3,7,10],[7,10,14]]] },
    'WARP MALFUNCTION': { bpm:134, root:43, scale:[0,2,3,7,10], lead:'sawtooth', bass:'square', cutoff:6800, mood:'glitch drive', progressions:[[[0,3,10],[2,7,12],[3,10,14],[0,7,10]],[[0,3,10],[7,10,15],[2,7,12],[3,10,14]]] },
    'REACTOR ROOM': { bpm:140, root:36, scale:[0,2,3,5,7,10], lead:'square', bass:'sawtooth', cutoff:2700, mood:'industrial', progressions:[[[0,3,7],[2,5,10],[3,7,12],[0,5,10]],[[0,3,7],[5,8,12],[3,7,10],[7,10,13]]] },
    'VOID BLOOM': { bpm:116, root:40, scale:[0,2,5,6,9], lead:'triangle', bass:'sine', cutoff:3900, mood:'alien bloom', progressions:[[[0,5,9],[2,6,11],[5,9,14],[0,6,11]],[[0,5,9],[6,11,14],[2,6,11],[5,9,14]]] },
  });
  const clamp = (value,min,max) => Math.max(min,Math.min(max,value));
  const midiToHz = note => 440*Math.pow(2,(note-69)/12);
  const choose = items => items[Math.floor(Math.random()*items.length)];

  class MusicalClock {
    constructor(context,bpm){this.ctx=context;this.reset(bpm);}
    reset(bpm,delay=.04){this.bpm=bpm;this.origin=this.ctx.currentTime+delay;this.nextTime=this.origin;this.absoluteStep=0;}
    get stepDuration(){return 60/this.bpm/STEPS_PER_BEAT;}
    quantize(steps=1){const now=this.ctx.currentTime+.006,index=Math.ceil((now-this.origin)/(this.stepDuration*steps));return Math.max(now,this.origin+index*this.stepDuration*steps);}
    advance(){const n=this.absoluteStep,tick={time:this.nextTime,absoluteStep:n,step:n%STEPS_PER_BAR,bar:Math.floor(n/STEPS_PER_BAR),beat:Math.floor((n%STEPS_PER_BAR)/STEPS_PER_BEAT),phrase:Math.floor(n/STEPS_PER_PHRASE)};this.absoluteStep++;this.nextTime+=this.stepDuration;return tick;}
  }

  class EventAggregator {
    constructor(flush){this.flush=flush;this.queue=[];this.timer=0;}
    add(event){this.queue.push(event);if(!this.timer)this.timer=setTimeout(()=>{this.timer=0;const group=this.queue.splice(0);if(group.length)this.flush(group);},72);}
    clear(){if(this.timer)clearTimeout(this.timer);this.timer=0;this.queue.length=0;}
  }

  class ArrangementEngine {
    constructor(composition){this.composition=composition;}
    request(section,boundary='bar',priority=1){const c=this.composition,p=c.pendingSection;if(section===c.section){if(p&&priority>=p.priority)c.pendingSection=null;return;}if(p&&p.priority>priority)return;c.pendingSection={section,boundary,priority};}
    consider(){const c=this.composition,e=c.energy;if(c.section===SECTIONS.DROP&&c.currentBar-c.sectionStartedBar>=4)return this.request(SECTIONS.RELEASE,'bar',3);if(c.section===SECTIONS.RELEASE&&c.currentBar-c.sectionStartedBar>=2)return this.request(e>.34?SECTIONS.GROOVE:SECTIONS.CALM,'bar',2);if(c.section===SECTIONS.CALM&&e>.2)this.request(SECTIONS.GROOVE,'bar',1);else if(c.section===SECTIONS.GROOVE&&e>.59)this.request(SECTIONS.BUILD,'phrase',1);else if(c.section===SECTIONS.BUILD&&e<.35)this.request(SECTIONS.GROOVE,'bar',1);else if(c.section===SECTIONS.GROOVE&&e<.15)this.request(SECTIONS.CALM,'phrase',1);}
    applyAt(tick){const c=this.composition,p=c.pendingSection;if(!p)return false;const ready=p.boundary==='beat'?tick.step%4===0:p.boundary==='bar'?tick.step===0:tick.absoluteStep%STEPS_PER_PHRASE===0;if(!ready)return false;c.section=p.section;c.sectionStartedBar=tick.bar;c.pendingSection=null;return true;}
  }

  class DynamicMusicEngine {
    constructor(context,{output,worldWidth=1000,debug=false}={}){
      this.ctx=context;this.output=output||context.destination;this.worldWidth=worldWidth;this.debug=debug;this.enabled=true;this.muted=false;this.running=false;this.paused=false;this.gameOver=false;this.theme=THEMES['NEON HORIZON'];this.themeName='NEON HORIZON';this.wave=1;
      this.clock=new MusicalClock(context,this.theme.bpm);this.timer=0;this.voiceCount=0;this.maxVoices=22;this.percussionTimes=[];this.melodicSlots=new Map();this.lastUpdate=0;this.activeEffects=new Set();this.noiseBuffer=this.makeNoiseBuffer(1);this.shaperCurve=this.makeSaturationCurve();
      this.composition=this.freshComposition();this.arrangement=new ArrangementEngine(this.composition);this.destroyAggregator=new EventAggregator(group=>this.consumeDestroyed(group));this.buildMix();
    }
    freshComposition(){return {bpm:this.theme.bpm,root:this.theme.root,scale:[...this.theme.scale],progression:choose(this.theme.progressions),currentBar:0,currentBeat:0,phraseIndex:0,section:SECTIONS.CALM,sectionStartedBar:0,pendingSection:null,intensity:.08,energy:.08,targetEnergy:.08,comboEnergy:0,destructionEnergy:0,multiballEnergy:0,eventEnergy:0,motif:[],secondaryMotif:[],melodyBuffer:[],motifAge:0,bassPattern:[0,null,null,null,0,null,null,null,0,null,null,null,0,null,null,null],drumPattern:{kick:[0,8],snare:[4,12],hat:[]},arpPattern:[0,4,8,12],activeLayers:new Set(['foundation']),signals:{paddle:0,wall:0,obstacle:0,laser:0,explosion:0},lastMajorEvent:null};}
    buildMix(){const c=this.ctx;this.master=c.createGain();this.master.gain.value=.72;this.musicFilter=c.createBiquadFilter();this.musicFilter.type='lowpass';this.musicFilter.frequency.value=18000;this.musicFilter.Q.value=.3;this.compressor=c.createDynamicsCompressor();this.compressor.threshold.value=-15;this.compressor.knee.value=14;this.compressor.ratio.value=5;this.compressor.attack.value=.008;this.compressor.release.value=.19;this.drums=c.createGain();this.drums.gain.value=.88;this.bass=c.createGain();this.bass.gain.value=.72;this.harmony=c.createGain();this.harmony.gain.value=.27;this.melody=c.createGain();this.melody.gain.value=.56;this.arp=c.createGain();this.arp.gain.value=.42;this.impacts=c.createGain();this.impacts.gain.value=.62;this.bassDuck=c.createGain();this.bassDuck.gain.value=1;this.harmonyDuck=c.createGain();this.harmonyDuck.gain.value=1;this.bass.connect(this.bassDuck);this.bassDuck.connect(this.musicFilter);this.harmony.connect(this.harmonyDuck);this.harmonyDuck.connect(this.musicFilter);[this.drums,this.melody,this.arp,this.impacts].forEach(bus=>bus.connect(this.musicFilter));this.musicFilter.connect(this.master);this.master.connect(this.compressor);this.compressor.connect(this.output);}
    makeNoiseBuffer(seconds){const length=Math.floor(this.ctx.sampleRate*seconds),buffer=this.ctx.createBuffer(1,length,this.ctx.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<length;i++){const white=Math.random()*2-1;last=last*.78+white*.22;data[i]=white*.62+last*.38;}return buffer;}
    makeSaturationCurve(){const curve=new Float32Array(256);for(let i=0;i<curve.length;i++){const x=i*2/(curve.length-1)-1;curve[i]=Math.tanh(x*2.2);}return curve;}

    start(themeName='NEON HORIZON',wave=1){if(!this.enabled)return;this.running=true;this.paused=false;this.gameOver=false;this.setTheme(themeName,wave,true);this.composition=this.freshComposition();this.arrangement=new ArrangementEngine(this.composition);this.clock.reset(this.theme.bpm,.035);if(!this.timer)this.timer=setInterval(()=>this.scheduler(),25);this.rampMaster(.72,.08);this.onWaveStart(themeName,wave,true);}
    stop(){this.running=false;this.destroyAggregator.clear();if(this.timer){clearInterval(this.timer);this.timer=0;}this.rampMaster(.0001,.12);}
    setMuted(muted){this.muted=!!muted;this.rampMaster(this.muted?.0001:.72,this.muted?.04:.12);}
    pause(){if(!this.running||this.paused)return;this.paused=true;this.rampMaster(.035,.09);}
    resume(){if(!this.running||!this.paused)return;this.paused=false;this.clock.nextTime=this.ctx.currentTime+.035;this.rampMaster(this.muted?.0001:.72,.16);}
    rampMaster(value,duration){const t=this.ctx.currentTime,g=this.master.gain;g.cancelScheduledValues(t);g.setTargetAtTime(value,t,Math.max(.008,duration/4));}
    setTheme(name,wave=this.wave,immediate=false){const next=THEMES[name]||THEMES['NEON HORIZON'],changed=next!==this.theme;this.theme=next;this.themeName=THEMES[name]?name:'NEON HORIZON';this.wave=wave;this.clock.bpm=next.bpm;if(this.composition){this.composition.bpm=next.bpm;this.composition.root=next.root;this.composition.scale=[...next.scale];if(changed)this.composition.progression=choose(next.progressions);}if(changed&&!immediate){const t=this.ctx.currentTime,f=this.musicFilter.frequency;f.cancelScheduledValues(t);f.setValueAtTime(Math.max(650,f.value),t);f.exponentialRampToValueAtTime(650,t+.28);f.exponentialRampToValueAtTime(next.cutoff*2.8,t+1.05);this.transitionSweep(t);}}

    scheduler(){if(!this.enabled||!this.running||this.paused||this.muted||this.ctx.state!=='running')return;const horizon=this.ctx.currentTime+.14;if(this.clock.nextTime<this.ctx.currentTime-.2)this.clock.nextTime=this.ctx.currentTime+.025;while(this.clock.nextTime<horizon)this.scheduleTick(this.clock.advance());const cutoff=this.ctx.currentTime-.5;this.percussionTimes=this.percussionTimes.filter(t=>t>cutoff);for(const [key] of this.melodicSlots)if(Number(key)<cutoff)this.melodicSlots.delete(key);}
    scheduleTick(tick){const c=this.composition;c.currentBar=tick.bar;c.currentBeat=tick.beat;c.phraseIndex=tick.phrase;if(tick.absoluteStep%STEPS_PER_PHRASE===0)this.evolvePhrase();else if(tick.step===0)this.evolveBar();const changed=this.arrangement.applyAt(tick);if(changed){this.evolveDrums();this.evolveBass();this.performTransition(tick.time,c.section);}const section=this.gameOver?SECTIONS.RELEASE:c.section,step=tick.step,chord=this.currentChord(tick.bar);if(step===0&&tick.bar%2===0&&section!==SECTIONS.CALM&&section!==SECTIONS.RELEASE)this.padChord(tick.time,chord,this.clock.stepDuration*15,.055+c.energy*.045);if(c.drumPattern.kick.includes(step))this.kick(tick.time,step===0?.96:.76+c.energy*.14);if(c.drumPattern.snare.includes(step))this.snare(tick.time,section===SECTIONS.CALM?.42:.6);if(section===SECTIONS.CALM&&step===0)this.bassPulse(tick.time,this.theme.root+this.chordRoot(chord),.22);if(c.drumPattern.hat.includes(step))this.hat(tick.time,section===SECTIONS.DROP?.3:.2,step%4===2);const bassOffset=c.bassPattern[step];if(bassOffset!==null&&section!==SECTIONS.CALM)this.bassPulse(tick.time,this.theme.root+this.chordRoot(chord)+bassOffset,.31+c.energy*.25,{sub:this.activeEffects.has('bigBall')||this.activeEffects.has('unit'),acid:this.activeEffects.has('fart')||this.activeEffects.has('worm')});this.performMotifStep(tick,section);if(this.shouldArp(section)&&c.arpPattern.includes(step))this.performArp(tick.time,chord,step,section);if(this.activeEffects.has('pew')&&section!==SECTIONS.CALM&&step%2===1)this.pluck(tick.time,this.theme.root+31+(step%4),.045,(step%8)/7-.5,{short:true,bright:true,bus:this.arp});if(this.activeEffects.has('worm')&&step===0)this.glide(tick.time,this.theme.root,this.theme.root+7,this.clock.stepDuration*7,.15);}
    evolveBar(){const c=this.composition;c.energy+=(c.targetEnergy-c.energy)*.2;c.intensity=c.energy;if(!c.motif.length&&c.melodyBuffer.length)this.evolveMotif();this.arrangement.consider();}
    evolvePhrase(){const c=this.composition;c.energy+=(c.targetEnergy-c.energy)*.42;c.intensity=c.energy;this.arrangement.consider();this.evolveMotif();this.evolveDrums();this.evolveBass();c.motifAge++;for(const key of Object.keys(c.signals))c.signals[key]*=.35;c.destructionEnergy*=.55;c.eventEnergy*=.5;}
    evolveMotif(){const c=this.composition,input=c.melodyBuffer.splice(0);if(!input.length&&!c.motif.length)return;const useful=[];for(const event of input){const prior=useful[useful.length-1];if(!prior||prior.note!==event.note||Math.random()<.22)useful.push(event);}if(!c.motif.length&&useful.length){const picked=useful.slice(-6);while(picked.length<3){const source=picked[picked.length%useful.length];picked.push({note:this.nearbyScaleNote(source.note,picked.length),weight:source.weight});}c.motif=picked.map((e,i)=>({note:e.note,step:[0,3,6,8,11,14][i]}));c.motifAge=0;return;}if(!useful.length||Math.random()>.74)return;const next=c.motif.map(item=>({...item})),source=choose(useful),index=Math.floor(Math.random()*next.length),old=next[index].note;next[index].note=this.limitLeap(source.note,index?next[index-1].note:old);if(Math.random()<.35)next[index].step=clamp(next[index].step+(Math.random()<.5?-1:1),0,15);if(next.length<8&&useful.length>3&&Math.random()<.28)next.push({note:this.limitLeap(choose(useful).note,next[next.length-1].note),step:choose([5,9,13,15])});c.motif=next.sort((a,b)=>a.step-b.step);c.secondaryMotif=c.motif.map(item=>({note:item.note+7,step:(item.step+8)%16})).sort((a,b)=>a.step-b.step);c.motifAge=0;}
    nearbyScaleNote(note,offset){const pitch=(note-this.theme.root)%12,index=Math.max(0,this.theme.scale.indexOf(pitch)),degree=this.theme.scale[(index+offset)%this.theme.scale.length],octave=Math.floor((note-this.theme.root)/12)*12;return this.theme.root+octave+degree;}
    limitLeap(note,anchor){if(anchor===undefined)return note;while(note-anchor>7)note-=12;while(anchor-note>7)note+=12;return clamp(note,this.theme.root+12,this.theme.root+31);}
    evolveDrums(){const c=this.composition,s=c.section,signals=c.signals,kick=[0,8],snare=[4,12],hat=[];if(s!==SECTIONS.CALM)kick.push(choose(signals.paddle>2?[3,6,10,14]:[6,10,14]));if(s===SECTIONS.BUILD||s===SECTIONS.DROP||this.activeEffects.has('laserDisco'))kick.push(4,12);if(s===SECTIONS.GROOVE||s===SECTIONS.BUILD)for(let i=2;i<16;i+=4)hat.push(i);if(s===SECTIONS.DROP||this.activeEffects.has('panic'))for(let i=0;i<16;i+=2)hat.push(i);if(signals.wall>6)for(let i=1;i<16;i+=4)hat.push(i);if(signals.obstacle>2&&this.themeName==='REACTOR ROOM')snare.push(choose([2,10,14]));c.drumPattern={kick:[...new Set(kick)],snare:[...new Set(snare)],hat:[...new Set(hat)]};}
    evolveBass(){const c=this.composition,dense=c.section===SECTIONS.DROP||c.energy>.68,medium=c.section===SECTIONS.GROOVE||c.section===SECTIONS.BUILD,pattern=Array(16).fill(null);pattern[0]=0;pattern[8]=0;if(medium||dense){pattern[4]=0;pattern[12]=choose([0,7]);}if(dense){pattern[3]=0;pattern[6]=7;pattern[10]=choose([0,5,7]);pattern[14]=0;}if(this.activeEffects.has('tinyHands')){pattern[4]=null;pattern[12]=7;}c.bassPattern=pattern;}
    performMotifStep(tick,section){const c=this.composition;if(!c.motif.length||section===SECTIONS.CALM&&tick.bar%2===1)return;const hit=c.motif.find(item=>item.step===tick.step);if(hit&&(section!==SECTIONS.CALM||tick.step%4===0))this.pluck(tick.time,hit.note,section===SECTIONS.DROP?.24:.15+c.energy*.06,(tick.step/15)*1.1-.55,{bright:section!==SECTIONS.CALM,angry:this.activeEffects.has('angry')});if(section===SECTIONS.DROP){const counter=c.secondaryMotif.find(item=>item.step===tick.step);if(counter)this.pluck(tick.time,counter.note,.12,-(tick.step/15)*.8+.4,{short:true,bright:true,bus:this.arp});}}
    performArp(time,chord,step,section){const notes=chord.map(n=>this.theme.root+24+n),index=Math.floor(step/Math.max(1,section===SECTIONS.DROP?2:4))%notes.length;this.pluck(time,notes[index],section===SECTIONS.DROP?.15:.09,(step/15)*1.2-.6,{short:true,bright:true,bus:this.arp});}
    shouldArp(section){return (this.composition.multiballEnergy>.12||this.activeEffects.has('chain')||this.activeEffects.has('laserDisco'))&&(section===SECTIONS.BUILD||section===SECTIONS.DROP||this.composition.multiballEnergy>.45);}
    currentChord(bar){const p=this.composition.progression;return p[bar%p.length];}
    chordRoot(chord){return chord[0]||0;}
    quantized(divisions=4){return this.clock.quantize(Math.max(1,STEPS_PER_BEAT/divisions));}

    update({balls=1,combo=1,effects={}}={}){const now=performance.now();if(now-this.lastUpdate<90)return;this.lastUpdate=now;const c=this.composition;this.activeEffects=new Set(Object.entries(effects).filter(([,value])=>value>0).map(([key])=>key));c.comboEnergy=combo>=15?1:combo>=10?.82:combo>=8?.68:combo>=5?.52:combo>=3?.32:combo>=2?.18:0;c.multiballEnergy=clamp((balls-1)/20,0,1);const powerEnergy=clamp(this.activeEffects.size*.05,0,.28),destruction=clamp(c.destructionEnergy,0,.75);c.targetEnergy=this.gameOver?.06:clamp(.07+c.multiballEnergy*.35+c.comboEnergy*.34+powerEnergy+destruction*.22+c.eventEnergy*.24,.06,1);c.energy+=(c.targetEnergy-c.energy)*.12;c.intensity=c.energy;this.ballCount=balls;this.combo=combo;}
    compositionEvent(kind,amount=.05){const c=this.composition;c.signals[kind]=(c.signals[kind]||0)+1;c.eventEnergy=clamp(c.eventEnergy+amount,0,1);}
    onPaddleHit(){this.compositionEvent('paddle',.018);}
    onWallHit(_ball,wall){this.compositionEvent('wall',wall==='top'?.012:.006);}
    onObstacleHit(){this.compositionEvent('obstacle',.025);}
    onBrickHit(){this.compositionEvent('brick',.006);}
    onBrickDestroyed(brick,ball){this.destroyAggregator.add({x:(brick?.x||0)+(brick?.w||0)/2,y:brick?.y||0,tough:brick?.maxHp||1,speed:Math.hypot(ball?.vx||0,ball?.vy||0)});}
    consumeDestroyed(group){if(!this.running)return;const c=this.composition,count=group.length,x=group.reduce((s,e)=>s+e.x,0)/count,y=group.reduce((s,e)=>s+e.y,0)/count,tough=Math.max(...group.map(e=>e.tough)),note=this.noteFromPosition(x,y);c.melodyBuffer.push({note,weight:count+tough,time:performance.now()});if(c.melodyBuffer.length>24)c.melodyBuffer.splice(0,c.melodyBuffer.length-24);c.destructionEnergy=clamp(c.destructionEnergy+count*.025+tough*.01,0,1);c.eventEnergy=clamp(c.eventEnergy+count*.012,0,1);if(count>=4){const t=this.quantized(2);this.chordStab(t,this.currentChord(c.currentBar),count>9?.3:.2);if(count>8){this.fill(t,count>14?6:4);this.registerMajor('explosion-chain',count>14?1:.7);}}}
    onExplosion(brickCount=1,position={x:500},strength=1){const c=this.composition;c.signals.explosion+=brickCount;c.destructionEnergy=clamp(c.destructionEnergy+brickCount*.02,0,1);const t=this.quantized(2),x=position?.x??500;if(brickCount<4)this.bassPulse(t,this.theme.root,.3,{sub:strength>1.1});else{this.chordStab(t,this.currentChord(c.currentBar),clamp(.18+strength*.08,.18,.38));this.noiseImpact(t,clamp(.16+strength*.1,.16,.46),.2+strength*.1);}if(brickCount>=10||strength>=1.8)this.registerMajor('large-explosion',clamp(strength/2,0,1));if(brickCount>3)c.melodyBuffer.push({note:this.noteFromPosition(x,250),weight:brickCount,time:performance.now()});}
    onComboChanged(combo){this.combo=combo;if(combo>=15)this.registerMajor('high-combo',.72);else if(combo>=8)this.arrangement.request(SECTIONS.BUILD,'phrase',2);}
    onPowerupCollected(id){this.onPowerupActivated(id);}
    onPowerupActivated(id){const c=this.composition;c.eventEnergy=clamp(c.eventEnergy+.13,0,1);if(['moreBalls','multiballer'].includes(id)){this.registerMajor('multiball',.78);this.riser(this.quantized(2),.36);}else if(['nuclear','boom','chain'].includes(id))this.registerMajor(id,id==='nuclear'?1:.62);else if(id==='bigBall'||id==='unit'){const t=this.quantized(2);this.bassPulse(t,this.theme.root,.48,{sub:true});}else if(id==='fart'||id==='worm')this.bassPulse(this.quantized(2),this.theme.root+7,.4,{acid:true});else if(id==='portal')this.glide(this.quantized(2),this.theme.root+12,this.theme.root+24,.3);else if(id==='gravity')this.glide(this.quantized(2),this.theme.root+19,this.theme.root+14,.42);else if(id==='shotgun')this.fill(this.quantized(2),3);}
    onLaser(){this.compositionEvent('laser',.004);}
    onPortal(_ball,_from,to){this.composition.melodyBuffer.push({note:this.noteFromPosition(to?.x||500,100),weight:2,time:performance.now()});this.compositionEvent('portal',.035);}
    registerMajor(name,strength=1){const c=this.composition;c.lastMajorEvent=name;c.eventEnergy=clamp(c.eventEnergy+.3*strength,0,1);if(c.section===SECTIONS.BUILD||strength>.85)this.arrangement.request(SECTIONS.DROP,'bar',5);else this.arrangement.request(SECTIONS.BUILD,'bar',4);}
    onSmashEvent(name){const t=this.quantized(2),delay=name==='BIG CHUNGUS'?.18:.12;this.duckMusic(t,delay+.08,.13);this.riser(t,delay);this.registerMajor(name,1);this.arrangement.request(SECTIONS.DROP,'beat',10);if(name==='BIG CHUNGUS'){this.bassPulse(t+delay,this.theme.root,.56,{sub:true});this.kick(t+delay,1);this.noiseImpact(t+delay,.36,.34);}else if(name==='LASER DISCO'){this.activeEffects.add('laserDisco');this.fill(t,4);}else if(name==='BALL STORM'){this.fill(t,6);this.composition.multiballEnergy=1;}else if(name==='BRICKPOCALYPSE'){this.metallic(t+.04,.34,0);this.chordStab(t+delay,this.currentChord(this.composition.currentBar),.4);}else{this.activeEffects.add('panic');this.fill(t,8);}}
    onWaveStart(themeName,wave,initial=false){this.setTheme(themeName,wave,initial);const c=this.composition;this.gameOver=false;c.targetEnergy=.08;c.eventEnergy=0;c.destructionEnergy=0;c.progression=choose(this.theme.progressions);this.arrangement.request(SECTIONS.CALM,'beat',8);const t=this.quantized(2);this.riser(t,this.clock.stepDuration*2);this.pluck(t+this.clock.stepDuration*2,this.theme.root+24,.2,0,{bright:true});}
    onWaveClear(){const c=this.composition,t=this.quantized(2),root=this.theme.root+12;this.arrangement.request(SECTIONS.RELEASE,'beat',9);[7,3,0].forEach((n,i)=>this.pluck(t+i*this.clock.stepDuration,root+n,.2-i*.02,0,{bright:i===0}));this.chordStab(t+this.clock.stepDuration*3,this.currentChord(c.currentBar),.28);c.targetEnergy=.1;}
    onLifeLost(){const c=this.composition;this.destroyAggregator.clear();c.targetEnergy=.05;c.energy=Math.min(c.energy,.16);c.eventEnergy=0;c.destructionEnergy=0;c.multiballEnergy=0;c.comboEnergy=0;this.activeEffects.clear();this.arrangement.request(SECTIONS.RELEASE,'beat',10);const t=this.ctx.currentTime+.012;this.musicFilter.frequency.cancelScheduledValues(t);this.musicFilter.frequency.setValueAtTime(Math.max(600,this.musicFilter.frequency.value),t);this.musicFilter.frequency.exponentialRampToValueAtTime(180,t+.32);this.musicFilter.frequency.exponentialRampToValueAtTime(this.theme.cutoff*2,t+.82);this.glide(t,this.theme.root+12,this.theme.root-5,.45);}
    onBallRelaunch(){this.composition.targetEnergy=.08;this.arrangement.request(SECTIONS.CALM,'beat',8);this.pluck(this.quantized(2),this.theme.root+12,.16,0,{});}
    onGameOver(){const c=this.composition;this.destroyAggregator.clear();this.paused=false;this.clock.nextTime=this.ctx.currentTime+.035;this.gameOver=true;c.targetEnergy=.04;c.eventEnergy=0;this.activeEffects.clear();this.arrangement.request(SECTIONS.RELEASE,'beat',12);const t=this.quantized(2),root=this.theme.root+12;[7,3,0,-5].forEach((n,i)=>this.pluck(t+i*this.clock.stepDuration,root+n,.2-i*.025,0,{bright:i===0}));this.padChord(t+this.clock.stepDuration*4,this.currentChord(c.currentBar),3.2,.1);}

    performTransition(time,section){const target=section===SECTIONS.CALM?.34:section===SECTIONS.GROOVE?.58:section===SECTIONS.BUILD?.78:section===SECTIONS.DROP?1:.24;this.composition.energy=Math.max(this.composition.energy,target*.7);const f=this.musicFilter.frequency;f.cancelScheduledValues(time);f.setValueAtTime(Math.max(400,f.value),time);f.exponentialRampToValueAtTime(clamp(this.theme.cutoff*(.55+target*2),700,15000),time+this.clock.stepDuration*2);if(section===SECTIONS.DROP){this.kick(time,1);this.bassPulse(time,this.theme.root,.55,{sub:true});this.noiseImpact(time,.34,.32);}else if(section===SECTIONS.RELEASE)this.duckMusic(time,.2,.38);}
    duckForScare(duration=.9){const t=this.ctx.currentTime,g=this.master.gain;g.cancelScheduledValues(t);g.setTargetAtTime(.09,t,.015);g.setTargetAtTime(this.muted?.0001:.72,t+duration,.16);}
    duckMusic(time,duration,depth=.45){const g=this.master.gain;g.cancelScheduledValues(time);g.setTargetAtTime(depth,time,.012);g.setTargetAtTime(this.muted?.0001:.72,time+duration,.08);}
    sidechain(time){for(const bus of [this.bassDuck,this.harmonyDuck]){const g=bus.gain;g.cancelScheduledValues(time);g.setValueAtTime(1,time);g.exponentialRampToValueAtTime(.72,time+.012);g.exponentialRampToValueAtTime(1,time+.11);}}
    noteFromPosition(x,y=0){const normalized=clamp(x/this.worldWidth,0,1),index=Math.min(this.theme.scale.length-1,Math.floor(normalized*this.theme.scale.length)),octave=y<250?24:12;return this.theme.root+octave+this.theme.scale[index];}
    panFromX(x){return clamp((x/this.worldWidth-.5)*1.25,-.62,.62);}
    slot(time,limit=4){const key=time.toFixed(3),used=this.melodicSlots.get(key)||0;if(used>=limit)return false;this.melodicSlots.set(key,used+1);return true;}
    allowPercussion(){const now=this.ctx.currentTime;this.percussionTimes=this.percussionTimes.filter(t=>t>now-.09);if(this.percussionTimes.length>=8)return false;this.percussionTimes.push(now);return true;}
    panNode(value){if(this.ctx.createStereoPanner){const p=this.ctx.createStereoPanner();p.pan.value=clamp(value,-.72,.72);return p;}return this.ctx.createGain();}
    track(source){this.voiceCount++;source.addEventListener('ended',()=>{this.voiceCount=Math.max(0,this.voiceCount-1);},{once:true});}
    canVoice(count=1){return this.voiceCount+count<=this.maxVoices;}
    pluck(time,note,velocity=.2,pan=0,{short=false,bright=false,angry=false,bus=null}={}){if(!this.canVoice(2)||!this.slot(time))return;const c=this.ctx,dur=short?.16:.34,frequency=midiToHz(note),p=this.panNode(pan),filter=c.createBiquadFilter(),gain=c.createGain(),drive=c.createWaveShaper();filter.type='lowpass';filter.Q.value=bright?5.2:3.2;filter.frequency.setValueAtTime(Math.min(11000,this.theme.cutoff*(bright?1.65:1)),time);filter.frequency.exponentialRampToValueAtTime(480,time+dur);drive.curve=this.shaperCurve;drive.oversample='2x';gain.gain.setValueAtTime(.0001,time);gain.gain.exponentialRampToValueAtTime(velocity*(.92+Math.random()*.12),time+.008);gain.gain.exponentialRampToValueAtTime(.0001,time+dur);p.connect(filter);filter.connect(drive);drive.connect(gain);gain.connect(bus||this.melody);const a=c.createOscillator(),b=c.createOscillator();a.type=angry?'sawtooth':this.theme.lead;b.type='triangle';a.frequency.value=frequency;b.frequency.value=frequency*2;a.detune.value=-5+Math.random()*3;b.detune.value=5+Math.random()*4;a.connect(p);b.connect(p);a.start(time);b.start(time);a.stop(time+dur+.02);b.stop(time+dur+.02);this.track(a);this.track(b);}
    kick(time,velocity=.8){if(!this.allowPercussion()||!this.canVoice())return;this.sidechain(time);const c=this.ctx,o=c.createOscillator(),g=c.createGain();o.type=this.themeName==='REACTOR ROOM'?'square':'sine';o.frequency.setValueAtTime(this.themeName==='REACTOR ROOM'?155:132,time);o.frequency.exponentialRampToValueAtTime(42,time+.12);g.gain.setValueAtTime(Math.min(.72,velocity*.64),time);g.gain.exponentialRampToValueAtTime(.0001,time+.22);o.connect(g);g.connect(this.drums);o.start(time);o.stop(time+.24);this.track(o);}
    snare(time,velocity=.55){if(!this.allowPercussion()||!this.canVoice(2))return;const c=this.ctx,n=c.createBufferSource(),filter=c.createBiquadFilter(),g=c.createGain(),tone=c.createOscillator(),tg=c.createGain();n.buffer=this.noiseBuffer;filter.type='bandpass';filter.frequency.value=this.themeName==='REACTOR ROOM'?980:1750;filter.Q.value=.75;g.gain.setValueAtTime(velocity*.34,time);g.gain.exponentialRampToValueAtTime(.0001,time+.16);n.connect(filter);filter.connect(g);g.connect(this.drums);tone.type='triangle';tone.frequency.value=this.themeName==='ORBITAL STATIC'?210:165;tg.gain.setValueAtTime(velocity*.16,time);tg.gain.exponentialRampToValueAtTime(.0001,time+.11);tone.connect(tg);tg.connect(this.drums);n.start(time,Math.random()*.4,.18);tone.start(time);tone.stop(time+.13);this.track(n);this.track(tone);}
    hat(time,velocity=.22,open=false){if(!this.allowPercussion()||!this.canVoice())return;const c=this.ctx,n=c.createBufferSource(),hp=c.createBiquadFilter(),g=c.createGain();n.buffer=this.noiseBuffer;hp.type='highpass';hp.frequency.value=this.themeName==='VOID BLOOM'?5200:7200;g.gain.setValueAtTime(velocity,time);g.gain.exponentialRampToValueAtTime(.0001,time+(open?.1:.045));n.connect(hp);hp.connect(g);g.connect(this.drums);n.start(time,Math.random()*.7,open?.12:.06);this.track(n);}
    bassPulse(time,note,velocity=.42,{sub=false,acid=false}={}){if(!this.canVoice())return;const c=this.ctx,o=c.createOscillator(),filter=c.createBiquadFilter(),g=c.createGain(),drive=c.createWaveShaper();o.type=sub?'sine':this.theme.bass;o.frequency.value=midiToHz(note+(sub?-12:0));filter.type='lowpass';filter.Q.value=acid?11:2.2;filter.frequency.setValueAtTime(acid?950:680,time);filter.frequency.exponentialRampToValueAtTime(acid?180:240,time+.28);drive.curve=this.shaperCurve;g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(Math.min(.55,velocity),time+.014);g.gain.exponentialRampToValueAtTime(.0001,time+(sub?.75:.34));o.connect(filter);filter.connect(drive);drive.connect(g);g.connect(this.bass);o.start(time);o.stop(time+(sub?.8:.38));this.track(o);}
    padChord(time,intervals,duration=1.8,velocity=.15){if(!this.canVoice(3))return;const c=this.ctx,g=c.createGain(),filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=this.themeName==='VOID BLOOM'?1650:1150;g.gain.setValueAtTime(.0001,time);g.gain.linearRampToValueAtTime(velocity,time+.3);g.gain.setValueAtTime(velocity,time+Math.max(.35,duration-.4));g.gain.exponentialRampToValueAtTime(.0001,time+duration);filter.connect(g);g.connect(this.harmony);intervals.slice(0,3).forEach((offset,index)=>{const o=c.createOscillator();o.type=index===0?'triangle':'sawtooth';o.frequency.value=midiToHz(this.theme.root+12+offset);o.detune.value=(index-1)*8;o.connect(filter);o.start(time);o.stop(time+duration+.02);this.track(o);});}
    chordStab(time,intervals,velocity=.25){intervals.slice(0,3).forEach((offset,index)=>this.pluck(time,this.theme.root+12+offset,velocity*(1-index*.14),(index-1)*.24,{short:true,bright:true,bus:this.harmony}));}
    metallic(time,velocity=.25,pan=0){if(!this.canVoice(2)||!this.allowPercussion())return;const c=this.ctx,p=this.panNode(pan),g=c.createGain();g.gain.setValueAtTime(velocity,time);g.gain.exponentialRampToValueAtTime(.0001,time+.18);p.connect(g);g.connect(this.drums);[1,1.414].forEach((ratio,index)=>{const o=c.createOscillator();o.type='square';o.frequency.value=(index?620:438)*ratio;o.connect(p);o.start(time);o.stop(time+.2);this.track(o);});}
    noiseImpact(time,velocity=.35,duration=.24){if(!this.canVoice()||!this.allowPercussion())return;const c=this.ctx,n=c.createBufferSource(),filter=c.createBiquadFilter(),g=c.createGain();n.buffer=this.noiseBuffer;filter.type='lowpass';filter.frequency.setValueAtTime(7000,time);filter.frequency.exponentialRampToValueAtTime(240,time+duration);g.gain.setValueAtTime(velocity,time);g.gain.exponentialRampToValueAtTime(.0001,time+duration);n.connect(filter);filter.connect(g);g.connect(this.impacts);n.start(time,Math.random()*.4,duration);this.track(n);}
    glide(time,fromNote,toNote,duration=.3,pan=0){if(!this.canVoice())return;const c=this.ctx,o=c.createOscillator(),filter=c.createBiquadFilter(),g=c.createGain(),p=this.panNode(pan);o.type='sawtooth';o.frequency.setValueAtTime(midiToHz(fromNote),time);o.frequency.exponentialRampToValueAtTime(midiToHz(toNote),time+duration);filter.type='lowpass';filter.frequency.value=2100;filter.Q.value=6;g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(.18,time+.012);g.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(p);p.connect(filter);filter.connect(g);g.connect(this.impacts);o.start(time);o.stop(time+duration+.02);this.track(o);}
    riser(time,duration=.3){if(!this.canVoice())return;const c=this.ctx,n=c.createBufferSource(),bp=c.createBiquadFilter(),g=c.createGain();n.buffer=this.noiseBuffer;bp.type='bandpass';bp.frequency.setValueAtTime(500,time);bp.frequency.exponentialRampToValueAtTime(7500,time+duration);bp.Q.value=1.4;g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(.17,time+duration*.75);g.gain.exponentialRampToValueAtTime(.0001,time+duration);n.connect(bp);bp.connect(g);g.connect(this.impacts);n.start(time,0,duration+.02);this.track(n);}
    fill(time,hits=4){const spacing=this.clock.stepDuration/2;for(let i=0;i<hits;i++)this.snare(time+i*spacing,.28+i/hits*.2);}
    transitionSweep(time){this.noiseImpact(time+.12,.16,.55);this.glide(time+.18,this.theme.root-5,this.theme.root+12,.48);}
    debugState(){const c=this.composition;return {bpm:this.theme.bpm,theme:this.themeName,section:c.section,intensity:Number(c.energy.toFixed(2)),voices:this.voiceCount,combo:this.combo||1,balls:this.ballCount||1,bar:c.currentBar+1,phrase:c.phraseIndex+1,motif:c.motif.map(n=>n.note),root:this.theme.root,scale:[...this.theme.scale],mood:this.theme.mood};}
  }

  window.DynamicMusicEngine=DynamicMusicEngine;
  window.BALLS_OUT_MUSIC_THEMES=THEMES;
})();
